name: Generate Keystore

on:
  push:
    branches: [ "main", "master" ]

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Generate Keystore
      run: |
        keytool -genkey -v \
          -keystore upload-keystore.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias upload \
          -dname "CN=Traccar, OU=IT, O=YourCompany, L=City, S=State, C=US" \
          -storepass traccar123 \
          -keypass traccar123

    - name: Convert to Base64
      run: base64 upload-keystore.jks > keystore-base64.txt

    - name: Upload keystore artifacts
      uses: actions/upload-artifact@v4
      with:
        name: keystore-files
        path: |
          upload-keystore.jks
          keystore-base64.txt
